# Generated by Django 6.1.1 on 2026-09-09 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('response_time_hours', models.PositiveIntegerField(help_text='Max hours to first respond to an issue')),
                ('resolution_time_hours', models.PositiveIntegerField(help_text='Max hours to resolve an issue')),
                ('uptime_guarantee_percent', models.DecimalField(decimal_places=2, help_text='e.g. 99.9', max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Acts as the renewal date when this SLA is renewed')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slas', to='vendors.vendor')),
            ],
        ),
    ]
