# Generated by Django 6.1 on 2026-09-08 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_prefix', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='it_assets.assetcategory')),
            ],
            options={
                'verbose_name_plural': 'Asset categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('PROCURED', 'Procured'), ('RECEIVED', 'Received'), ('IN_STOCK', 'In stock'), ('ASSIGNED', 'Assigned'), ('IN_USE', 'In use'), ('UNDER_REPAIR', 'Under repair'), ('RETURNED', 'Returned'), ('REASSIGNED', 'Reassigned'), ('RETIRED', 'Retired'), ('DISPOSED', 'Disposed')], default='IN_STOCK', max_length=20)),
                ('current_department', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='it_assets.assetcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_image', models.ImageField(blank=True, upload_to='asset_tags/')),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='it_assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_number', models.CharField(help_text='HR / employee ID number', max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, help_text='Link to their login account, if they have one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_department', models.CharField(blank=True, max_length=100)),
                ('to_department', models.CharField(blank=True, max_length=100)),
                ('from_location', models.CharField(blank=True, max_length=150)),
                ('to_location', models.CharField(blank=True, max_length=150)),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='it_assets.asset')),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='it_assets.employee')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='it_assets.employee')),
            ],
            options={
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='it_assets.employee'),
        ),
        migrations.CreateModel(
            name='EquipmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('condition', models.CharField(default='Good', max_length=50)),
                ('accessories', models.TextField(blank=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='it_assets.asset')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_received', to='it_assets.employee')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(auto_now_add=True)),
                ('condition', models.CharField(max_length=50)),
                ('missing_accessories', models.TextField(blank=True)),
                ('damage_notes', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_record', to='it_assets.equipmentissue')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField()),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_reports', to='it_assets.asset')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('po_reference', models.CharField(blank=True, max_length=50)),
                ('delivery_date', models.DateField()),
                ('inspection_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_accepted', models.PositiveIntegerField()),
                ('quantity_rejected', models.PositiveIntegerField(default=0)),
                ('serial_numbers', models.TextField(blank=True, help_text='Comma-separated serials, required if is_serialized=True')),
                ('is_serialized', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='it_assets.assetcategory')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='it_assets.goodsreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verification_date'],
            },
        ),
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True)),
                ('warranty_checked', models.BooleanField(default=False)),
                ('under_warranty', models.BooleanField(blank=True, null=True)),
                ('repair_action', models.TextField(blank=True)),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('test_result', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10)),
                ('status', models.CharField(choices=[('FAULT_REPORTED', 'Fault reported'), ('TECHNICIAN_ASSIGNED', 'Technician assigned'), ('DIAGNOSIS', 'Diagnosis'), ('WARRANTY_CHECK', 'Warranty check'), ('VENDOR_SERVICE_CENTER', 'At vendor service center'), ('REPAIR_IN_PROGRESS', 'Repair in progress'), ('TESTING', 'Testing'), ('RETURNED_TO_USER', 'Returned to user'), ('CLOSED', 'Closed')], default='FAULT_REPORTED', max_length=25)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('fault_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_records', to='it_assets.faultreport')),
                ('service_center_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor')),
                ('technician_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs_handled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('quantity_issued', models.PositiveIntegerField(default=0)),
                ('quantity_damaged', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=0)),
                ('maximum_stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('reorder_quantity', models.PositiveIntegerField(default=0)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='it_assets.assetcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryVerificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('physical_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('found_status', models.CharField(choices=[('FOUND', 'Found'), ('NOT_FOUND', 'Not found'), ('DAMAGED', 'Damaged'), ('RELOCATED', 'Relocated'), ('MISTAGGED', 'Mistagged')], max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='it_assets.asset')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='it_assets.inventoryverification')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='it_assets.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.PositiveIntegerField()),
                ('physical_quantity', models.PositiveIntegerField()),
                ('difference', models.IntegerField(editable=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INVESTIGATING', 'Investigating'), ('ADJUSTED', 'Adjusted')], default='PENDING', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('adjustment_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='it_assets.inventoryverification')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='it_assets.stockitem')),
            ],
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='it_assets.stockitem'),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ISSUE', 'Issue'), ('RETURN', 'Return'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment'), ('DISPOSAL', 'Disposal')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for stock in, negative for stock out')),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='it_assets.stockitem')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_provider', models.CharField(max_length=150)),
                ('warranty_type', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('terms', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='it_assets.asset')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateField(auto_now_add=True)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=15)),
                ('resolution', models.TextField(blank=True)),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='it_assets.warranty')),
            ],
            options={
                'ordering': ['-claim_date'],
            },
        ),
    ]
